version: '3'
services:
    balancer:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    server_1:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start"

    server_2:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start"

    server_3:
        working_dir: /app
        image: node
        volumes:
            - ./app:/app
        command: bash -c "npm i && npm start"